import Head from "next/head";
import { useState, useEffect } from "react";
import { BsArrowUpShort } from "react-icons/bs";
import {
  Header,
  About,
  Contact,
  Footer,
  Hero,
  Marque,
  Project,
  Service,
  Skills,
} from "@/components";

export default function Home() {
  const [scrollPosition, setScrollPosition] = useState(0);

  useEffect(() => {
    function handleScroll() {
      setScrollPosition(window.scrollY);
    }

    window.addEventListener("scroll", handleScroll);

    // Cleanup the event listener
    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
  }, []);

  const showClass = scrollPosition >= 300 ? "show__link" : "";

  return (
    <>
      <Head>
        <title>Sakil Ahmed</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main>
        <Header />
        <Hero />
        <Marque />
        <About />
        <Skills />
        <Service />
        <Project />
        <Contact />
        <Footer />
        <a className={`top__link ${showClass}`} href={"#header"}>
          <BsArrowUpShort />
        </a>
      </main>
    </>
  );
}
