import Head from "next/head";
import { useState, useEffect } from "react";
import { BsArrowUpShort } from "react-icons/bs";
import {
  Header,
  About,
  Contact,
  Footer,
  Hero,
  Marque,
  Project,
  Service,
  Skills,
} from "@/components";
import Intro from "@/components/IntroTextAnimation/Intro";

export default function Home() {
  const [scrollPosition, setScrollPosition] = useState(0);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    function handleScroll() {
      setScrollPosition(window.scrollY);
    }
    window.addEventListener("scroll", handleScroll);

    const interval = setInterval(() => {
      setIsLoading(false);
    }, 4500);

    // Cleanup the event listener
    return () => {
      window.removeEventListener("scroll", handleScroll);
      clearInterval(interval);
    };
  }, []);

  const showClass = scrollPosition >= 300 ? "show__link" : "";

  return (
    <>
      <Head>
        <title>Sakil Ahmed</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main>
        {isLoading ? (
          <Intro />
        ) : (
          <>
            <Header />
            <Hero />
            <Marque />
            {/* <About /> */}
            <Skills />
            {/* <Service /> */}
            <Project />
            <Contact />
            <Footer />
            <a className={`top__link ${showClass}`} href={"#header"}>
              <BsArrowUpShort />
            </a>
          </>
        )}
      </main>
    </>
  );
}
